### ISSUE TITLE
Setting up new environment leads to compile error

### ISSUE THREAD

**Issue by digidigo** [OriginProtocol/origin-js#155] opened 2018-05-06 01:53 UTC
I am new the project and am getting my environment up and running. 

**npm install** fails on compiling the contracts with the errors at the bottom of this issue. 

It seems to be related to the recent change: [Pegged contracts to a specific Solidity version](https://github.com/OriginProtocol/origin-js/commit/fdfa0fb9d59b83e7f88fcf779cb3c79ea32497dc)

Reverting that change, or bumping the version to the same version as the identity contracts,  allows the project to compile again and run. I'd open a PR , but the change is so recent it certainly meant to address some other issue. 

Errors: 

/Users/dclements/crypto/origin/origin-js/contracts/contracts/Purchase.sol:1:1: SyntaxError: Source file requires different compiler version (current compiler is 0.4.23+commit.124ca40d.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.4.21;
^---------------------^
,/Users/dclements/crypto/origin/origin-js/contracts/contracts/PurchaseLibrary.sol:1:1: SyntaxError: Source file requires different compiler version (current compiler is 0.4.23+commit.124ca40d.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.4.21;
^---------------------^
,/Users/dclements/crypto/origin/origin-js/contracts/contracts/Listing.sol:1:1: SyntaxError: Source file requires different compiler version (current compiler is 0.4.23+commit.124ca40d.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.4.21;
^---------------------^
,/Users/dclements/crypto/origin/origin-js/contracts/contracts/ListingsRegistry.sol:1:1: SyntaxError: Source file requires different compiler version (current compiler is 0.4.23+commit.124ca40d.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.4.21;
^---------------------^
,/Users/dclements/crypto/origin/origin-js/contracts/contracts/Migrations.sol:1:1: SyntaxError: Source file requires different compiler version (current compiler is 0.4.23+commit.124ca40d.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.4.21;
^---------------------^
,/Users/dclements/crypto/origin/origin-js/contracts/contracts/UserRegistry.sol:1:1: SyntaxError: Source file requires different compiler version (current compiler is 0.4.23+commit.124ca40d.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.4.21;

**Comment by nick** [comment] 2018-05-12 17:31
I believe this has been fixed in the latest release... please reopen if not.

**Closed by nick** 2018-05-12 17:31 UTC
Labels: bug, origin.js, smart contracts, solidity

**Comment by zhilongliu** [comment] 2018-06-20 09:57
hi, 
  I also encountered this issue on my testing environment.  I just replace the version number "pragma solidity 0.4.23" as "0.4.24" in all contracts of ./origin-js/contracts/contracts/(Listening.sol .etc.), but didn't modify the contracts under ./origin-js/contracts/contracts/identity/ (ClaimHolder.sol  .etc.).  Then 'truffle compile' works well.

I'm still confusing that both the contracts under ./origin-js/contracts/contracts/* and ./origin-js/contracts/contracts/identity/* are the same version of "pragma solidity 0.4.23", why only the contracts of ./origin-js/contracts/contracts/* would complain the "SyntaxError"?

would you reproduce the above situation?

My env:
$ truffle version
Truffle v4.1.11 (core: 4.1.11)
Solidity v0.4.24 (solc-js)

thanks,
Zhilong

**Comment by zhilongliu** [comment] 2018-06-20 10:17
Oh, I see the root cause, I would send a pr for it.

Thanks 
Zhilong

**Comment by joshfraser** [comment] 2018-06-20 12:44
@zhilongliu invited you as a contributor.
