### ISSUE TITLE
Clarify scope of the docker container

### ISSUE THREAD

**Issue by tyleryasaka** [OriginProtocol/origin-js#230] opened 2018-06-07 21:21 UTC
We've talked about a lot of potential use cases for the docker container. We should probably clarify what exactly we want it to do so we can find the simplest way to do it.

For example, what processes should the container actually run? I think we all agree that it should be running the bridge server. But should it run the origin-js dev environment as well?

See @wanderingstan 's comment: https://github.com/OriginProtocol/origin-js/pull/227#issuecomment-395566380

**Comment by wanderingstan** [comment] 2018-06-07 21:38
Paging @ambertch :) 👆

**Comment by tyleryasaka** [comment] 2018-06-07 21:48
I think for origin-js and/or demo-dapp dev purposes, running the bridge server in a container makes the most sense. There really isn't a need to run origin-js in this container, now that I think about it.

What I'm wondering about is *bridge-server* development - often this is done alongside a running origin-js instance. Maybe that's out of scope here; I think my initial impression was that we would have this environment that would spin up all our various pieces and connect them all for local development. The container would include demo-dapp, origin-js, and bridge-server, and could be used for development on any of them. Another advantage might be that we could eventually do end-to-end testing this way. Maybe that's too ambitious right now?

**Comment by ambertch** [comment] 2018-06-07 22:55
One thing that would be different if just the bridge server is run in the container is the networking  (I think it's just passing in `--net="host"` to the docker run command) since the bridge server will be talking to blockchain/IPFS running on the host rather than in the container.

I recall the original primary use case was to ease origin-js development, so both running just the bridge server or having it run some of the components spun up by origin-js accomplishes that.

After the discussion about integration testing started, my impression was also that we would have all the various pieces in that sandbox. I also think that having an "Origin-in-A-Box" setup makes things easier for either new platform or partner dapp developers, particularly if the developer's core experience is in one part of the stack. The developers of say 30 partner dapps can all spin up the same environment and expect to see the same example application, same data in the database, etc. Likewise, for bug reproduction / support cases.

**Comment by cuongdo** [comment] 2018-06-07 23:17
I really like the "Origin in a box" idea. It's very useful to have a fully working setup with minimal effort. It took me a while to setup bridge-server locally the first time I did it.

**Comment by tyleryasaka** [comment] 2018-06-08 03:02
Posted a couple of thoughts here: https://github.com/OriginProtocol/origin-js/pull/232#issuecomment-395631447

**Comment by micahalcorn** [comment] 2018-08-31 21:29
Closing this since THE BOX has moved on in a lot of ways 📦

**Closed by micahalcorn** 2018-08-31 21:29 UTC
Labels: dev environment, discussion
